### ISSUE TITLE
Rework wiki articles

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [SayakMukhopadhyay/pax-wiki-progress-notes#1]
The article about [Pax Dei](https://paxdeimmo.wiki/wiki/Pax_Dei), not the main page, needs to be reworked.

Since I am also maintaining the [Pax Dei wikipedia page](https://en.wikipedia.org/wiki/Pax_Dei_(video_game)), I want to have all information that is present in the wikipedia page to also be in this page. The question is if it should be a 1-1 sync or if our wiki should contain additional info. Having additional info can make ensuring all the info from the wikipedia page to be here a bit difficult since we will need to hunt.

I am personally inclined to include additional info in the page but we need to ensure that we follow the policy of incorporating additions/changes to the wikipedia page into this page.
- [x] Pax Dei - Will contain info from Design Pillars and Inspiration. Also contain Development info, Tech, Platforms
- [x] FAQ - Stuff from the Extended FAQ needs to be added
- [x] Buildings
- [x] Player Characters
- [x] Economy
- [x] Lore
- [x] Gear
- [x] Weapon
- [x] Crafting
- [x] Gathering
- [x] Gameplay - Should be a broad article about the mechanisms and things that don't need a page of its own like Solo Play, Social Systems and maybe PVE and PVP
- [x] Combat
- [x] Magic
- [x] The World
- [x] Map - Includes information from Zones, Nature, and the World

**Comment by SayakMukhopadhyay** [comment]
Overall a lot of pages needs to be created or updated. Here's a tentative list of pages that should be created

* Pax Dei - Will contain info from `Design Pillars` and `Inspiration`. Also contain `Development` info, `Tech`, `Platforms`
* FAQ - Stuff from the `Extended FAQ` needs to be added
* Buildings
* Player Characters
* Economy
* Lore
* Gear and Weapons
* Crafting
* Gathering
* Leatherworking
* Gameplay - Should be a broad article about the mechanisms and things that don't need a page of its own like `Solo Play`, `Social Systems` and maybe `PVE` and `PVP`
* Trading
* Combat
* Magic
* Map - Includes information from `Zones, Nature, and the World`
* Heartlands - Info and details about the heartland mechanism
* Contested provinces
* Galia - Details about Galia itself and maybe some associated Lore

**Comment by NyasakiAT** [comment]
**Player Characters** might need to be rename into something that explains it better
**Gameplay** should link in some way to the other pages mentioned

Not sure If we really should leave **Galia** in there since the Map could link to this Page

**Comment by ShalimarPaxDei** [comment]
Gallia should be a subpage of Regions, and not on the main nav tree.

**Comment by SayakMukhopadhyay** [comment]
> Gallia should be a subpage of Regions, and not on the main nav tree. 

Honestly, mediawiki doesn't really have a subpage concept and all pages are stored at the same level. Once the pages are created, we can play around with the structuring of which goes where.

**Comment by ShalimarPaxDei** [comment]
What I mean by a subpage is that it doesn't have a direct link from the main page. You access the subpages through links within the articles.

**Comment by SayakMukhopadhyay** [comment]
Oh ok. In fact, a majority of the pages will be sub pages.

**Comment by SayakMukhopadhyay** [comment]
[Building](https://paxdeimmo.wiki/wiki/Building) has been completed. Please check for missing info from 

1. https://paxdeimmo.wiki/wiki/Old_Building
2. https://paxdeimmo.wiki/wiki/Official_Frequently_Asked_Questions#Building[9]
3. https://paxdeimmo.wiki/wiki/Extended_FAQ#Building,_Plots,_Crafting,_Economy

and any other article I am missing.

**Comment by ShalimarPaxDei** [comment]
Of this list, I'll take the articles on Economy and Trading.

**Comment by eikkuu** [comment]
I can create crafting stations, I have the datamined json with accurate recipes

**Comment by eikkuu** [comment]
On this matter, I have also all the other json files which are related to effects, spells etc

**Comment by ShalimarPaxDei** [comment]
> I can create crafting stations, I have the datamined json with accurate recipes

Let's be careful with datamined info. We don't want to reveal anything that isn't public info. Mainframe frowns on datamining. Articles that contain NDA info need to be held on personal devices until the NDA is lifted, then they can be copy/pasted into the wiki at that time.

**Comment by eikkuu** [comment]
can pages being unlisted?

**Comment by NyasakiAT** [comment]
Doesnt matter, its still released and still could be datamined

**Comment by SayakMukhopadhyay** [comment]
Let's not add any datamined info for now. Whether we do it later or not will depend on how MF feels about it. For now, no datamined info please.

**Comment by eikkuu** [comment]
Yeah the plan is not add any datamined info, the plan was to add info that I have in the recordings which is much better structured in the files

**Comment by SayakMukhopadhyay** [comment]
I started working on the Lore today and quickly realised it might not have been the best idea. A lot of the info is in flowery language and some of the existing data doesn't have sources. For now, I have created the [Lore page](https://paxdeimmo.wiki/wiki/Lore) with a starting paragraph. We will work on this over the coming weeks.

Data from:
1. https://paxdeimmo.wiki/wiki/Old_Lore
2. https://sway.cloud.microsoft/aIsW61TSLa0PSSjV?ref=Link&loc=play
3. https://docs.google.com/document/d/1yU41Aw0JHF84CNP3cxrRsYR8BwIZ2PihaJk6zhroZf0/edit?pli=1

**Comment by eikkuu** [comment]
Yeah, probably for Lore is just best to have the info what they have shared. Its quite hard to interpred it for "proper" language :)

**Comment by SayakMukhopadhyay** [comment]
> Yeah, probably for Lore is just best to have the info what they have shared. Its quite hard to interpred it for "proper" language :)

Just to ensure we are on the same page. Wikis are for articles and I don't want the wiki to contain info dumps. So, the goal of the lore page would be rephrase all the lore that MF has provided. Once books are released, we can have a page for each book, which can contain its content but that's different.

**Comment by eikkuu** [comment]
These look now following, its still needs some fine-tuning but I felt that most of the old quotes were not that useful anymore.
https://paxdeimmo.wiki/wiki/Crafting
https://paxdeimmo.wiki/wiki/Old_Crafting

**Comment by eikkuu** [comment]
I wanna maybe move the crafting stations under the each skill but they can now be there for time being.

**Comment by ShalimarPaxDei** [comment]
Notes on Economy article:
Economy

Economy to be 100% player driven: https://playpaxdei.com/en-us/faq/monetization 
Economy article
Links 1-4 broken
Links 5-6 ok
Links 7-9 broken
Links 10-11 ok
Links 12-16 broken
Links 17-18 ok
Link 19 broken

We discussed the broken links and they go to currently hidden pages. Decided to leave those references.

**Comment by ShalimarPaxDei** [comment]
Social Systems notes:
Developer posts:

Clans:
https://discord.com/channels/1071081786962088018/1077535952500699146/1153924491454464121
https://discord.com/channels/1071081786962088018/1077535952500699146/1098276600052711536
https://discord.com/channels/1071081786962088018/1077535952500699146/1083840304433598505
https://discord.com/channels/1071081786962088018/1077535952500699146/1083832615573917806
https://discord.com/channels/1071081786962088018/1077535952500699146/1080549842348163142
https://discord.com/channels/1071081786962088018/1136992548188082206/1175438114437738536
https://discord.com/channels/1071081786962088018/1082631596605177882/1174449578033029190
https://discord.com/channels/1071081786962088018/1077535952500699146/1180490243049279488

https://support.playpaxdei.com/hc/en-us/articles/16046312868253-How-to-Clans

Guilds
https://discord.com/channels/1071081786962088018/1077535952500699146/1180490243049279488

Groups
https://support.playpaxdei.com/hc/en-us/articles/16174315446429-How-to-Groups

**Comment by SayakMukhopadhyay** [comment]
I have reworked the articles to the best I could. I am attaching a PFD of the extended FAQ that we can use in future if necessary. Closing this issue.

[Old Extended FAQ - Pax Dei Wiki.pdf](https://github.com/SayakMukhopadhyay/pax-wiki-progress-notes/files/15051177/Old.Extended.FAQ.-.Pax.Dei.Wiki.pdf)
